# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Exports
export DOTFILES="${ZDOTDIR:-$HOME}/.dotfiles"
export TERM="screen-256color"

# Hide Homebrew emojis
export HOMEBREW_NO_EMOJI=1

# Notes
export NOTES_FOLDER=~/notes

# Base16 Shell
BASE16_SCHEME="default"
BASE16_SHELL="$DOTFILES/zsh/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL

# Node
export NODE_PATH=/usr/local/lib/node_modules:$HOME/.node/lib/node_modules

# PATH
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:$DOTFILES/bin
export PATH=$PATH:$HOME/.rbenv/bin
export PATH=$PATH:/usr/local/share/npm/bin
export PATH=$PATH:$HOME/.node/bin
