# Include ~/.zprezto-themes/ to fpath
fpath=(${ZDOTDIR:-$HOME}/.zprezto-themes/ $fpath)

# Source Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Edit current command
autoload edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

# Incremental search in vi-mode
bindkey '^r' history-incremental-search-backward

# Source alias and utils files
for config_file ($DOTFILES/**/aliases.zsh) source $config_file
for util_file ($DOTFILES/**/utils.zsh) source $util_file

# Local files to be sourced if exists
if [[ -s "${ZDOTDIR:-$HOME}/.zshrc.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshrc.local"
fi

if [[ -s "${ZDOTDIR:-$HOME}/.zshenv.local" ]]; then
  source "${ZDOTDIR:-$HOME}/.zshenv.local"
fi
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
